- name: Install Docker if not already installed
  apt:
    name: docker.io
    state: present
  when: ansible_distribution == 'Ubuntu'

- name: Start Docker Service
  service:
    name: docker
    state: started

- name: Pull Splunk Docker Image
  docker_image:
    name: splunk/splunk:latest
    state: present

- name: Run Splunk Container
  docker_container:
    name: splunk
    image: splunk/splunk:latest
    ports:
      - "8000:8000"  # Web UI
      - "8088:8088"  # HEC
      - "8089:8089"  # Management Port
    env:
      SPLUNK_START_ARGS: --accept-license
      SPLUNK_PASSWORD: "{{ splunk_pass }}"
    detach: yes
    state: started
